### ISSUE TITLE
How do I sign up to be an official member?

### ISSUE THREAD

**Issue by timothylimyl** [Machine-Learning-Tokyo/__init__#6]
Hi, I am very interested to join the zoom session and discuss new exciting papers in the domain of Deep Learning.  How do I go about signing up for it?

**Comment by jmlipman** [comment]
Hello Timothy!

We typically gather the second (sometimes third) Sunday of the month, and you are more than welcome to join!
We announce the sessions on Twitter [1], and on Slack. Additionally, if you follow MLT at Meetup, you will get emails whenever MLT organizes any session, including init : )

To join, you just need to find the specific meetup page of the session, click on "Join" and you will see the Zoom link.

[1]: [@MLT](https://twitter.com/__MLT__) [@Miguel](https://twitter.com/jmlipman) [@Jayson](https://twitter.com/JsonMathsAI)
[2]: https://www.meetup.com/Machine-Learning-Tokyo/

**Comment by timothylimyl** [comment]
Okay sweet, I have joined the meetup group. Look forward to the next sess!
